// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {models} from '../models';

export function Connect(arg1:Array<string>):Promise<void>;

export function Delete(arg1:types.MsgCert):Promise<string>;

export function FetchAll():Promise<Array<types.RetMsgCert>>;

export function FetchPubKey():Promise<string>;

export function GenerateAlias(arg1:string):Promise<string>;

export function GenerateAvatar(arg1:string):Promise<string>;

export function GetModConfig():Promise<models.ModConfig>;

export function GetModerationLogs():Promise<Array<models.ModLogEntry>>;

export function GetOnlineMods():Promise<Array<string>>;

export function GetRelayStatus():Promise<string>;

export function ModAuthentication(arg1:string):Promise<boolean>;

export function RegenKeys():Promise<string>;

export function Report(arg1:types.MsgCert,arg2:any):Promise<string>;

export function SaveGoogleApiKey(arg1:string):Promise<void>;

export function SaveModConfig(arg1:models.ModConfig):Promise<void>;

export function SendInput(arg1:string):Promise<string|Array<types.ModCert>>;

export function TitleBarTheme(arg1:boolean):Promise<void>;
