// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function FetchAll() {
  return window['go']['main']['App']['FetchAll']();
}

export function FetchMessageReports() {
  return window['go']['main']['App']['FetchMessageReports']();
}

export function FetchPubKey() {
  return window['go']['main']['App']['FetchPubKey']();
}

export function GenerateAlias(arg1) {
  return window['go']['main']['App']['GenerateAlias'](arg1);
}

export function GenerateAvatar(arg1) {
  return window['go']['main']['App']['GenerateAvatar'](arg1);
}

export function GetModConfig() {
  return window['go']['main']['App']['GetModConfig']();
}

export function GetModerationLogs() {
  return window['go']['main']['App']['GetModerationLogs']();
}

export function GetOnlineMods() {
  return window['go']['main']['App']['GetOnlineMods']();
}

export function GetRelayAddr() {
  return window['go']['main']['App']['GetRelayAddr']();
}

export function GetRelayStatus() {
  return window['go']['main']['App']['GetRelayStatus']();
}

export function LogToFile(arg1) {
  return window['go']['main']['App']['LogToFile'](arg1);
}

export function ManualModerate(arg1, arg2) {
  return window['go']['main']['App']['ManualModerate'](arg1, arg2);
}

export function ModAuthentication(arg1) {
  return window['go']['main']['App']['ModAuthentication'](arg1);
}

export function RegenKeys() {
  return window['go']['main']['App']['RegenKeys']();
}

export function Report(arg1, arg2) {
  return window['go']['main']['App']['Report'](arg1, arg2);
}

export function SaveGoogleApiKey(arg1) {
  return window['go']['main']['App']['SaveGoogleApiKey'](arg1);
}

export function SaveModConfig(arg1) {
  return window['go']['main']['App']['SaveModConfig'](arg1);
}

export function SendInput(arg1) {
  return window['go']['main']['App']['SendInput'](arg1);
}

export function TitleBarTheme(arg1) {
  return window['go']['main']['App']['TitleBarTheme'](arg1);
}
