// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Connect(arg1:Array<string>):Promise<void>;

export function FetchAll():Promise<Array<string>>;

export function FetchMessagesByDate(arg1:number):Promise<void>;

export function FetchPubKey():Promise<string>;

export function FetchTimestamp(arg1:string):Promise<Array<string>>;

export function GenerateAlias(arg1:string):Promise<string>;

export function GenerateAvatar(arg1:string):Promise<string>;

export function GetModConfig():Promise<models.ModConfig>;

export function GetModerationLogs():Promise<Array<models.ModLogEntry>>;

export function GetRelayStatus():Promise<string>;

export function ModAuthentication(arg1:string):Promise<boolean>;

export function RegenKeys():Promise<string>;

export function SaveModConfig(arg1:models.ModConfig):Promise<void>;

export function SendInput(arg1:string):Promise<string>;

export function StreamMessages():Promise<void>;

export function TitleBarTheme(arg1:boolean):Promise<void>;
