// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function FetchAll() {
  return window['go']['main']['App']['FetchAll']();
}

export function FetchMessagesByDate(arg1) {
  return window['go']['main']['App']['FetchMessagesByDate'](arg1);
}

export function FetchPubKey() {
  return window['go']['main']['App']['FetchPubKey']();
}

export function FetchTimestamp(arg1) {
  return window['go']['main']['App']['FetchTimestamp'](arg1);
}

export function GenerateAlias(arg1) {
  return window['go']['main']['App']['GenerateAlias'](arg1);
}

export function GenerateAvatar(arg1) {
  return window['go']['main']['App']['GenerateAvatar'](arg1);
}

export function GetModConfig() {
  return window['go']['main']['App']['GetModConfig']();
}

export function GetModerationLogs() {
  return window['go']['main']['App']['GetModerationLogs']();
}

export function GetRelayStatus() {
  return window['go']['main']['App']['GetRelayStatus']();
}

export function ModAuthentication(arg1) {
  return window['go']['main']['App']['ModAuthentication'](arg1);
}

export function RegenKeys() {
  return window['go']['main']['App']['RegenKeys']();
}

export function SaveModConfig(arg1) {
  return window['go']['main']['App']['SaveModConfig'](arg1);
}

export function SendInput(arg1) {
  return window['go']['main']['App']['SendInput'](arg1);
}

export function StreamMessages() {
  return window['go']['main']['App']['StreamMessages']();
}

export function TitleBarTheme(arg1) {
  return window['go']['main']['App']['TitleBarTheme'](arg1);
}
