// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchAll():Promise<Array<string>>;

export function FetchTimestamp(arg1:string):Promise<Array<string>>;

export function SendInput(arg1:string):Promise<string>;
