// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function FetchAll() {
  return window['go']['main']['App']['FetchAll']();
}

export function FetchTimestamp(arg1) {
  return window['go']['main']['App']['FetchTimestamp'](arg1);
}

export function GetRelayStatus() {
  return window['go']['main']['App']['GetRelayStatus']();
}

export function SendInput(arg1) {
  return window['go']['main']['App']['SendInput'](arg1);
}
